GET http://localhost:8080/sampleApplicationController?id=7
### POST REQUEST

POST http://localhost:8080/sampleApplicationController
Content-Type: application/json

{
  "description": "Japan"
}
### PUT REQUEST
PUT http://localhost:8080/sampleApplicationController
Content-Type: application/json

{
  "id": 11,
  "description": "India"
}

### DELETE REQUEST
DELETE http://localhost:8080/sampleApplicationController?id=11